# version: "3.8"

services:
  backend:
    build:
      context: ./back-end
    container_name: my-back-end
    env_file:
      - ./back-end/.env
    ports:
      - "${PORT}:3000"
    restart: always

  nginx:
    build:
      # Chuyển context lên tận project gốc để Docker có thể nhìn thấy cả front-end và nginx folder
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: my-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always